FROM ubuntu:16.04

MAINTAINER Weston Crewe "westondcrewe@gmail.com"

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN python -m pip install -r requirements.txt 

COPY . /app

ENTRYPOINT [ "python" ]

CMD [ "app.py" ]
